version: '3.9'

services:

  nginx:
    image: nginx:1.21.6
    container_name: 'nginx-container-dev'
    restart: always
    working_dir: /app
    ports:
      - '8080:80'
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../../app/thumbs/:/app/thumbs
      - ../../app/upload/:/app/upload
    links:
      - node-app-service

  node-app-service:
    build:
      context: .
      dockerfile: node-app.docker
    ports:
      - '3000:3000'
      - '9229:9229'
    working_dir: /app
    container_name: 'node-app-container-dev'
    volumes:
      - ../../app:/app
      - ../../app/upload/:/app/upload
      - ../../app/thumbs/:/app/thumbs
    links:
      - mongodb-service
    command: 'npm run start:debug'
    hostname: 'node-app-service'
    environment:
      NODE_ENV: 'dev'
      APP_SECRET_FILE: '/run/secrets/APP_SECRET_FILE'
      EMAIL_NO_REPLY: 'noreply@localhost.ru' # NEVER COMMIT THIS STUFF!
      EMAIL_SENDER_API_KEY_FILE: '/run/secrets/EMAIL_SENDER_API_KEY_FILE'# NEVER COMMIT THIS STUFF!
      MONGO_INITDB_ROOT_USERNAME_FILE: '/run/secrets/MONGO_INITDB_ROOT_USERNAME_FILE'
      MONGO_INITDB_ROOT_PASSWORD_FILE: '/run/secrets/MONGO_INITDB_ROOT_PASSWORD_FILE'
      MONGO_DATABASE_NAME: 'chatwheel'
      MONGO_DATABASE_PORT: '27017'
      MONGO_DATABASE_REPLICA_SET: 'rs_chatwheel'
      PORT: '3000'
      EMAIL_LINK_HOST: 'localhost:4200'
      UPLOAD_DIRECTORY: '/app/upload'
      IMAGE_THUMB_DIRECTORY: '/app/thumbs'
      MAX_UPLOAD_FILE_SIZE: '7340032' # 7M
      RESTORE_PASSWORD_REQUEST_INTERVAL: 120 #How long should the user wait before they would have a chance to request a new password-restore key(is seconds)
      USER_NEARBY_SEARCH_MAX_RADIUS_M: 30000
      CHAT_ROULETTE_OFFER_AWAIT_TIME: 30000
      FACEBOOK_APP_ID_FILE: '/run/secrets/FACEBOOK_APP_ID_FILE'
      FACEBOOK_APP_SECRET_FILE: '/run/secrets/FACEBOOK_APP_SECRET_FILE'
    secrets:
      - APP_SECRET_FILE
      - EMAIL_SENDER_API_KEY_FILE
      - MONGO_INITDB_ROOT_USERNAME_FILE
      - MONGO_INITDB_ROOT_PASSWORD_FILE
      - FACEBOOK_APP_ID_FILE
      - FACEBOOK_APP_SECRET_FILE


  mongodb-service:
    image: mongo:4.0.10-xenial
    container_name: 'mongo-db-container-dev'
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - chatwheel_db_dev:/data/db
    environment:
      MONGO_INITDB_DATABASE: 'chatwheel'
      MONGO_INITDB_ROOT_USERNAME_FILE: '/run/secrets/MONGO_INITDB_ROOT_USERNAME_FILE'
      MONGO_INITDB_ROOT_PASSWORD_FILE: '/run/secrets/MONGO_INITDB_ROOT_PASSWORD_FILE'
    command: mongod --replSet rs_chatwheel
    secrets:
      - MONGO_INITDB_ROOT_USERNAME_FILE
      - MONGO_INITDB_ROOT_PASSWORD_FILE

volumes:
  chatwheel_db_dev:

secrets:
  APP_SECRET_FILE:
    file: app-secret.txt

  EMAIL_SENDER_API_KEY_FILE:
    file: email-sender-api-key.txt

  MONGO_INITDB_ROOT_USERNAME_FILE:
    file: mongo-user-name.txt

  MONGO_INITDB_ROOT_PASSWORD_FILE:
    file: mongo-password.txt

  FACEBOOK_APP_ID_FILE:
    file: facebook-app-id.txt

  FACEBOOK_APP_SECRET_FILE:
    file: facebook-app-secret.txt

